version: '3.4'

networks:
    employeesapinetwork:    
  
services:
  employeesapi:
    container_name: employeesapi
    image: ${DOCKER_REGISTRY-}employeesapi
    build:
      context: .
      dockerfile: EmployeesAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sql-server
    networks:
     - employeesapinetwork

  sql-server:
    container_name: employeeDB
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: <strong_password>
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - ./ .containers/db-data:/var/opt/mssql/data
    networks:
     - employeesapinetwork

    